### ISSUE TITLE
"Can't use facebook-login" and "react-native-vector-icons" together

### ISSUE THREAD

**Issue by NJoyLifeXx** [magus/react-native-facebook-login#124]
Hi everyone,

For some reason I can't have both modules running together, if only one of them is installed it is all fine. I think it is due to the gradle dependencies, not allowing them to work together. Part of the log file I am getting is:

17 error Windows_NT 10.0.10586
react-native-vector-icons
23 error Failed at the fSpot@0.0.1 start script 'node node_modules/react-native/local-cli/cli.js start'.

Thanks for the help in advance!

**Comment by emmanuellmota** [comment]
+1

**Comment by lwhiteley** [comment]
im using both together but im on a mac

please ensure you have the latest version of this module and react-native-vector-icons and also make sure you are using react-native 0.33or higher

then follow the troubleshooting section: 
https://github.com/magus/react-native-facebook-login/tree/master/android#troubleshooting

**Comment by emmanuellmota** [comment]
Thanks @lwhiteley, solved this error:

> `Could not expand ZIP 'D:\GitHub\FSpot\node_modules\react-native-facebook-login
\android\build\outputs\aar\react-native-facebook-login-release.aar'.`

but, app still closing on click in Facebook Login Button, here is the logcat:
> `10-01 15:40:10.863 18047 18183 I FBLoginPermissions: adding permission: email
10-01 15:40:10.863 18047 18183 I FBLoginPermissions: adding permission: user_friends
10-01 15:40:10.863 18047 18183 I FBLoginPermissions: Using: [email, user_friends]
10-01 15:40:10.863 18047 18183 I FBLoginBehavior: Using for login: NATIVE_WITH_FALLBACK
10-01 15:40:10.880   804  1635 I ActivityManager: START u0 {act=NATIVE_WITH_FALLBACK cmp=com.rnfapp/com.facebook.FacebookActivity (has extras)} from uid 10100 on display 0
10-01 15:40:10.886   804  1070 E Sensors : Acc old sensor_state 129, new sensor_state : 128 en : 0
10-01 15:40:11.019 18047 18047 D AndroidRuntime: Shutting down VM
10-01 15:40:11.021 18047 18047 E AndroidRuntime: FATAL EXCEPTION: main
10-01 15:40:11.021 18047 18047 E AndroidRuntime: Process: com.rnfapp, PID: 18047
10-01 15:40:11.021 18047 18047 E AndroidRuntime: Theme: themes:{default=overlay:com.baranovgroup.nstyledark, iconPack:com.baranovgroup.nstyledark, com.android.systemui=overlay:com.baranovgroup.nstyledark, com.android.systemui.navbar=overlay:com.baranovgroup.nstyledark}
10-01 15:40:11.021 18047 18047 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
10-01 15:40:11.021 18047 18047 E AndroidRuntime:        at com.facebook.login.LoginClient.getLogger(LoginClient.java:367)
10-01 15:40:11.021 18047 18047 E AndroidRuntime:        at com.facebook.login.LoginClient.logAuthorizationMethodComplete(LoginClient.java:417)
10-01 15:40:11.021 18047 18047 E AndroidRuntime:        at com.facebook.login.LoginClient.tryNextHandler(LoginClient.java:200)
10-01 15:40:11.021 18047 18047 E AndroidRuntime:        at com.facebook.login.GetTokenLoginMethodHandler.getTokenCompleted(GetTokenLoginMethodHandler.java:119)
10-01 15:40:11.021 18047 18047 E AndroidRuntime:        at com.facebook.login.GetTokenLoginMethodHandler$1.completed(GetTokenLoginMethodHandler.java:74)
10-01 15:40:11.021 18047 18047 E AndroidRuntime:        at com.facebook.internal.PlatformServiceClient.callback(PlatformServiceClient.java:157)
10-01 15:40:11.021 18047 18047 E AndroidRuntime:        at com.facebook.internal.PlatformServiceClient.handleMessage(PlatformServiceClient.java:141)
10-01 15:40:11.021 18047 18047 E AndroidRuntime:        at com.facebook.internal.PlatformServiceClient$1.handleMessage(PlatformServiceClient.java:62)
10-01 15:40:11.021 18047 18047 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
10-01 15:40:11.021 18047 18047 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
10-01 15:40:11.021 18047 18047 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5471)
10-01 15:40:11.021 18047 18047 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-01 15:40:11.021 18047 18047 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-01 15:40:11.021 18047 18047 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-01 15:40:11.021 18047 18047 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
10-01 15:40:11.023   804  1644 W ActivityManager:   Force finishing activity com.rnfapp/com.facebook.FacebookActivity
10-01 15:40:11.027   804  1644 W ActivityManager:   Force finishing activity com.rnfapp/.MainActivity
10-01 15:40:12.949 18047 18047 I Process : Sending signal. PID: 18047 SIG: 9
10-01 15:40:12.961   804   913 D OpenGLRenderer: endAllStagingAnimators on 0x97f23b00 (RippleDrawable) with handle 0x937c68a0
10-01 15:40:12.988  2552  2552 D TeslaUnread: onStartCommand() called with: intent = [Intent { cmp=com.teslacoilsw.notifier/.NotificationService (has extras) }], flags = [0], startId = [7], lastStartTime = [54483]
10-01 15:40:13.021   804  1634 I WindowState: WIN DEATH: Window{3910259 u0 com.rnfapp/com.facebook.FacebookActivity}
10-01 15:40:13.021   804  1381 D GraphicsStats: Buffer count: 7
10-01 15:40:13.024   804  3077 I WindowState: WIN DEATH: Window{5057c28 u0 com.rnfapp/com.rnfapp.MainActivity}
10-01 15:40:13.055   804  1381 I ActivityManager: Process com.rnfapp (pid 18047) has died
10-01 15:40:13.174   804   826 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0`

And when I open in Android Studio, show this error:
> `Error:Execution failed for task ':react-native-facebook-login:mergeDebugAndroidTestResources'.
> Error: com.android.builder.internal.aapt.AaptException: Failed to crunch file C:\Users\emman\Documents\ReactNative\rnfapp\node_modules\react-native-facebook-login\android\build\intermediates\exploded-aar\com.facebook.android\facebook-android-sdk\4.10.1\res\drawable-xhdpi\com_facebook_tooltip_black_background.9.png into C:\Users\emman\Documents\ReactNative\rnfapp\node_modules\react-native-facebook-login\android\build\intermediates\res\merged\androidTest\debug\drawable-xhdpi\com_facebook_tooltip_black_background.9.png`

I'm using Windows 10, I have not tried the Mac yet.
*sorry for my English

**Comment by lwhiteley** [comment]
can you use master. i updated the fbsdk but its not published yet and make the necessary updates to your android manifest and strings.xml

**Comment by emmanuellmota** [comment]
Is working! Thank you so much!

And my last error: Failed to crunch file... is a Windows limitation (Maximum File Path Length Limitation), solved with:

> `// file: android/build.gradle`
> `allprojects {
    buildDir = "C:/tmp/${rootProject.name}/${project.name}"
    ...
}`

**Comment by lwhiteley** [comment]
thats great. Thanks for sharing the solution!
