### ISSUE TITLE
FATAL EXEPTION - java.lang.RuntimeException

### ISSUE THREAD

**Issue by grafosecondo** [magus/react-native-facebook-login#241]
Hi everyone,

right after I updated grandle to v3.3 I am experiencing the following error everytime I try to complete a Facebook login. The App crashes and the login is not completed.

I double checked the install procedure and the manifest seems all good. How can I solve this?

Thank you in advance for any help.

> E: FATAL EXCEPTION: main
   Process: com.app, PID: 5445
   java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=64206, result=-1, data=Intent { (has extras) }} to activity {com.app/com.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4089)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132)
       at android.app.ActivityThread.-wrap20(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at com.xxsnakerxx.socialauth.SocialAuthModule$1.onSuccess(SocialAuthModule.java:74)
       at com.xxsnakerxx.socialauth.SocialAuthModule$1.onSuccess(SocialAuthModule.java:69)
       at com.facebook.login.LoginManager.finishLogin(LoginManager.java:597)
       at com.facebook.login.LoginManager.onActivityResult(LoginManager.java:221)
       at com.facebook.login.LoginManager$1.onActivityResult(LoginManager.java:164)
       at com.facebook.internal.CallbackManagerImpl.onActivityResult(CallbackManagerImpl.java:82)
       at com.xxsnakerxx.socialauth.SocialAuthModule.onActivityResult(SocialAuthModule.java:57)
       at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:261)
       at com.facebook.react.XReactInstanceManagerImpl.onActivityResult(XReactInstanceManagerImpl.java:627)
       at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:149)
       at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:77)
       at android.app.Activity.dispatchActivityResult(Activity.java:6932)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4085)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132) 
       at android.app.ActivityThread.-wrap20(ActivityThread.java) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533) 
       at android.os.Handler.dispatchMessage(Handler.java:102) 
       at android.os.Looper.loop(Looper.java:154) 
       at android.app.ActivityThread.main(ActivityThread.java:6119) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by grafosecondo** [comment]
Hi again,
 
I tried this solution
https://github.com/magus/react-native-facebook-login/issues/134

And verified the code after this Facebook FAQ
https://developers.facebook.com/docs/react-native/faq#faq_532433693628214

Still the error keeps showing up. Any clue?

Thank you

**Comment by khjde1207** [comment]
I have the same problem
`
<application>
....
</application>
<meta-data        android:name="com.facebook.sdk.ApplicationId"     android:value="@string/fb_app_id"/>
`
change  ->

`
<application>
....
<meta-data        android:name="com.facebook.sdk.ApplicationId"     android:value="@string/fb_app_id"/> 
</application>
`
