### ISSUE TITLE
App Crashing Android

### ISSUE THREAD

**Issue by brkrtp** [magus/react-native-facebook-login#267]
App crashing when click login button.

İm sure manifest and Mainapplication.java. Ios working successfull, ım using FBLoginManager

 `FBLoginManager.loginWithPermissions(["email","user_friends"]...`

**Comment by maggialejandro** [comment]
I'm getting the same error, on some devices/emulators..

```javascript
FBLoginManager.loginWithPermissions(['email'], callback)
```

react-native 0.45.1
react-native-facebook-login 1.6.0 (I was getting the same error on 1.5.0)

On FB dev console it shows this warning:

API Graph v2.3 is getting deprecated on 10 July, 2017
API Graph v2.4 is getting deprecated on 09 October, 2017

<img width="986" alt="captura de pantalla 2017-09-15 a la s 12 52 55" src="https://user-images.githubusercontent.com/3394748/30491902-28798ee6-9a15-11e7-8d48-6a8df3d26a43.png">
<img width="1038" alt="captura de pantalla 2017-09-15 a la s 12 53 07" src="https://user-images.githubusercontent.com/3394748/30491897-27838bae-9a15-11e7-8b8b-3b04d0699e1a.png">

**Comment by maggialejandro** [comment]
The App crashes when FB App is not installed.
It works if you set set login behavior to WebView.
```javascript
FBLoginManager.setLoginBehavior(FBLoginManager.LoginBehaviors.WebView);
```

If you set it to Web it throws me this error:

```bash
09-15 15:50:30.896 24134-24259/com.package I/react-native-sentry: captureEvent '{ NativeMap: {"level":"log","category":"console","message":"llega 1","timestamp":1505501430.983} }'
09-15 15:50:30.897 24134-24259/com.package I/FBLoginPermissions: adding permission: email
09-15 15:50:30.897 24134-24259/com.package I/FBLoginPermissions: Using: [email]
09-15 15:50:30.897 24134-24259/com.package I/FBLoginBehavior: Using for login: WEB_ONLY
                                                                          
                                                                          --------- beginning of system
09-15 15:50:31.009 24134-24209/com.package V/FA: Recording user engagement, ms: 26361
09-15 15:50:31.009 24134-24209/com.package V/FA: Using measurement service
09-15 15:50:31.010 24134-24209/com.package V/FA: Connecting to remote service
09-15 15:50:31.036 24134-24209/com.package I/FA: Tag Manager is not found and thus will not be used
09-15 15:50:31.078 24134-24209/com.package D/FA: Logging event (FE): _e, Bundle[{_o=auto, _et=26361, _sc=MainActivity, _si=-3499979482635146208}]
09-15 15:50:31.118 24134-24134/com.package V/FA: onActivityCreated
09-15 15:50:31.261 24134-24141/com.package W/art: Suspending all threads took: 108.554ms
09-15 15:50:31.328 24134-24209/com.package V/FA: Using measurement service
09-15 15:50:31.328 24134-24209/com.package V/FA: Connection attempt already in progress
09-15 15:50:31.328 24134-24209/com.package V/FA: Activity paused, time: 14849477
09-15 15:50:31.373 24134-24209/com.package V/FA: Using measurement service
09-15 15:50:31.373 24134-24209/com.package V/FA: Connection attempt already in progress
09-15 15:50:31.373 24134-24209/com.package V/FA: Activity resumed, time: 14849838
09-15 15:50:31.616 24134-24134/com.package I/Choreographer: Skipped 32 frames!  The application may be doing too much work on its main thread.
09-15 15:50:31.660 24134-24209/com.package D/FA: Connected to remote service
09-15 15:50:31.661 24134-24209/com.package V/FA: Processing queued up service tasks: 3
09-15 15:50:31.692 24134-24141/com.package W/art: Suspending all threads took: 21.078ms
09-15 15:50:31.718 24134-24134/com.package V/FA: onActivityCreated
09-15 15:50:31.731 24134-24134/com.package D/AndroidRuntime: Shutting down VM
09-15 15:50:31.817 24134-24209/com.package V/FA: Screen exposed for less than 1000 ms. Event not sent. time: 445
09-15 15:50:31.817 24134-24209/com.package V/FA: Activity paused, time: 14850135
09-15 15:50:35.741 24134-24134/com.package W/GAv4: syncDispatchLocalHits timed out: java.util.concurrent.TimeoutException
09-15 15:50:35.746 24134-24134/com.package E/io.sentry.android.event.helper.AndroidEventBuilderHelper: Error getting Proguard UUIDs.
                                                                                                                   java.io.FileNotFoundException: sentry-debug-meta.properties
                                                                                                                       at android.content.res.AssetManager.openAsset(Native Method)
                                                                                                                       at android.content.res.AssetManager.open(AssetManager.java:347)
                                                                                                                       at android.content.res.AssetManager.open(AssetManager.java:321)
                                                                                                                       at io.sentry.android.event.helper.AndroidEventBuilderHelper.getProGuardUuids(AndroidEventBuilderHelper.java:157)
                                                                                                                       at io.sentry.android.event.helper.AndroidEventBuilderHelper.helpBuildingEvent(AndroidEventBuilderHelper.java:73)
                                                                                                                       at io.sentry.SentryClient.runBuilderHelpers(SentryClient.java:109)
                                                                                                                       at io.sentry.SentryClient.sendEvent(SentryClient.java:162)
                                                                                                                       at io.sentry.Sentry.capture(Sentry.java:160)
                                                                                                                       at io.sentry.SentryUncaughtExceptionHandler.uncaughtException(SentryUncaughtExceptionHandler.java:48)
                                                                                                                       at com.google.android.gms.analytics.ExceptionReporter.uncaughtException(Unknown Source)
                                                                                                                       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
                                                                                                                       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
                                                                                                                   
                                                                                                                   
                                                                                                                   --------- beginning of crash
09-15 15:50:35.874 24134-24134/com.package E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.package, PID: 24134
                                                                         java.lang.NoSuchMethodError: No virtual method launchUrl(Landroid/app/Activity;Landroid/net/Uri;)V in class Landroid/support/customtabs/CustomTabsIntent; or its super classes (declaration of 'android.support.customtabs.CustomTabsIntent' appears in /data/app/com.package-1/base.apk)
                                                                             at com.facebook.internal.CustomTab.openCustomTab(CustomTab.java:50)
                                                                             at com.facebook.CustomTabMainActivity.onCreate(CustomTabMainActivity.java:67)
                                                                             at android.app.Activity.performCreate(Activity.java:6662)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                             at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
09-15 15:50:36.884 24134-24467/com.package E/GAv4: Successfully bound to service but never got onServiceConnected callback
```

**Comment by brkrtp** [comment]
Im fixed problem, my facebook app setting is wrong. I'm setting true and done fixed.

**Comment by claykohut** [comment]
@brkrtp which facebook app setting did you fix?

**Comment by marcojr** [comment]
It crashes for me too...and I've facebook app installed on android and also adding FBLoginManager.setLoginBehavior(FBLoginManager.LoginBehaviors.WebView); don't make any difference.
