### ISSUE TITLE
Could you please update the readme file on how to do setup for android ?

### ISSUE THREAD

**Issue by Sharathnasa** [magus/react-native-facebook-login#37]
Hello Magus,

Thanks for the plugin. Could you please include the steps that we need to follow to do setup in android if possible. Thank you. 

Regards,
Sharath

**Comment by chagasaway** [comment]
+1 for this

**Comment by lwhiteley** [comment]
sorry a link to this should have been in the readme

https://github.com/magus/react-native-facebook-login/blob/master/Android.md

**Comment by Sharathnasa** [comment]
No Problem, Iwhiteley. Thanks. If i come across any doubts or i need any clarification i will let you know. Thanks

Regards,
Sharath

**Comment by Sharathnasa** [comment]
Hello Iwhiteley,

I have followed the set-up mentioned in the .md file for android. I created the new react-native project and added the react-native fb login module using npm and followed the setup for android. Then synced the application. I have also added the app id and all. But when i try to run, the app is getting forced closed by display below error in the logcat.
error:
``````
com.facebooklogin E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                   Process: com.facebooklogin, PID: 22019
                                                                   java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                       at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at java.lang.Thread.run(Thread.java:841)
                                                                    Caused by: java.lang.NullPointerException
                                                                       at com.facebook.react.ReactInstanceManager.createAllViewManagers(ReactInstanceManager.java:395)
                                                                       at com.facebook.react.CoreModulesPackage.createNativeModules(CoreModulesPackage.java:54)
                                                                       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:546)
                                                                       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:515)
                                                                       at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:71)
                                                                       at com.facebook.react.ReactInstanceManager$ReactContextInitAsyncTask.doInBackground(ReactInstanceManager.java:156)
                                                                       at com.facebook.react.ReactInstanceManager$ReactContextInitAsyncTask.doInBackground(ReactInstanceManager.java:142)
                                                                       at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                       at java.lang.Thread.run(Thread.java:841) 
11-22 11:55:47.087 22019-22019/com.facebooklogin W/unknown:React: Unable to dispatch keyboard events in JS as the react instance has not been attached
`````````
This is my index.android.js file:

/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 */
'use strict';

var React = require('react-native');


var {NativeModules} = require('react-native');
var FBLogin = require('react-native-facebook-login');
//var FBLoginManager = React.FBLoginManager; // if needed

//eg.
<FBLogin
    onLogin={function(e){console.log(e)}}
    onLogout={function(e){console.log(e)}}
    onCancel={function(e){console.log(e)}}
    onPermissionsMissing={function(e){console.log(e)}}/>



var {
  AppRegistry,
  StyleSheet,
  Text,
  View,
} = React;

var FaceBookLogin = React.createClass({
  render: function() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.android.js
        </Text>
        <Text style={styles.instructions}>
          Shake or press menu button for dev menu
        </Text>
      </View>
    );
  }
});

var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('FaceBookLogin', () => FaceBookLogin);
`````````

Please let me know where i'm doing wrong. Thank you.

Regards,
SharathNasa

**Comment by Sharathnasa** [comment]
Hello Iwhiteley,

Thanks for the plugin. I was able to use the login  and logout functionality. But in the logcat in the android studio, i noticed the below warning message. What does this mean? Could you please explain if possible.

``````
"Uncaught TypeError: Cannot call method 'schedule' of undefined", source: https://m.facebook.com/v2.5/dialog/oauth?redirect_uri=fbconnect%3A%2F%2Fsuccess&display=touch&scope=email%2Cpublic_profile&response_type=token%2Csigned_request&default_audience=friends&return_scopes=true&client_id=1655109748098228&ret=login&sdk=android-4.6.0&ext=1448216697&hash=AeafZ_sFxvRMB3RN&refsrc=https%3A%2F%2Fm.facebook.com%2Flogin.php&refid=9&_rdr (1)

```````

Regards,
SharathNasa

**Comment by niftylettuce** [comment]
Can you please put this link in Readme already?  It would take you 30 seconds.
