### ISSUE TITLE
Unknown source file : com.android.dex.DexException: Multiple dex files define Lbolts/AggregateException;

### ISSUE THREAD

**Issue by Overload119** [magus/react-native-facebook-login#88]
```
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Lbolts/AggregateException;
Unknown source file : 	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file : 	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file : 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file : 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file : 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file : 	at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file : 	at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file : 	at com.android.dx.command.Main.main(Main.java:106)
```

I'm getting this issue on Android when trying to setup the Facebook SDK with this library.
I'll update this post as I figure out more...

**Comment by Overload119** [comment]
The Android SDK asks to add this line, but I removed it, and that's how I fixed this issue.

```diff
dependencies {
    compile project(':react-native-facebook-login')
    compile project(':react-native-vector-icons')
    compile project(':react-native-android-tablayout')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:0.19.+"
-   compile "com.facebook.android:facebook-android-sdk:[4,5)"
}
```
